# docker-compose.yml
version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: user_behavior_api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: user_behavior_nginx
    ports:
      - "443:443"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge